[package]
name = "momentor"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
debug = false
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_asset_loader = "0.16.1"
bevy_egui = "0.20.2"
bevy_pixel_camera = "0.4.1"
bevy_prototype_debug_lines = "0.10.1"
bevy_rapier2d = "0.21.0"
rand = "0.8.5"
